#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Advanced ML Trading Bot Trainer
- Fetches 50k+ historical candles
- Calculates advanced technical indicators (RSI, MACD, BB, Volatility)
- Trains XGBoost model for direction prediction
- Runs rigorous Backtest with dynamic risk management
- Generates detailed performance report
"""

import pandas as pd
import numpy as np
import ccxt
from datetime import datetime, timedelta
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

# --- Configuration ---
SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'SOL/USDT']
TIMEFRAME = '1h'
LIMIT = 50000  # Fetch 50k candles
TRAIN_SPLIT = 0.8
INITIAL_BALANCE = 10000  # USDT
RISK_PER_TRADE = 0.01  # 1% risk
STOP_LOSS_PCT = 0.015  # 1.5%
TAKE_PROFIT_PCT = 0.030  # 3.0%

print("🚀 Starting Advanced ML Trading Bot Training & Backtest...")
print(f"📊 Fetching {LIMIT} candles for {SYMBOLS} on {TIMEFRAME} timeframe...")

# --- 1. Data Collection ---
def fetch_data(symbol, limit):
    exchange = ccxt.binance()  # Using Binance for deep history
    ohlcv = exchange.fetch_ohlcv(symbol, timeframe=TIMEFRAME, limit=limit)
    df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df.set_index('timestamp', inplace=True)
    return df

data_cache = {}
for symbol in SYMBOLS:
    try:
        df = fetch_data(symbol, LIMIT)
        data_cache[symbol] = df
        print(f"✅ Fetched {len(df)} candles for {symbol}")
    except Exception as e:
        print(f"❌ Error fetching {symbol}: {e}")

if not data_cache:
    raise Exception("No data fetched. Check internet connection or API limits.")

# --- 2. Feature Engineering (Technical Indicators) ---
def add_indicators(df):
    # Moving Averages
    df['sma_20'] = df['close'].rolling(window=20).mean()
    df['sma_50'] = df['close'].rolling(window=50).mean()
    df['ema_12'] = df['close'].ewm(span=12, adjust=False).mean()
    df['ema_26'] = df['close'].ewm(span=26, adjust=False).mean()
    
    # RSI
    delta = df['close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    df['rsi'] = 100 - (100 / (1 + rs))
    
    # MACD
    df['macd'] = df['ema_12'] - df['ema_26']
    df['macd_signal'] = df['macd'].ewm(span=9, adjust=False).mean()
    df['macd_hist'] = df['macd'] - df['macd_signal']
    
    # Bollinger Bands
    df['bb_middle'] = df['close'].rolling(window=20).mean()
    bb_std = df['close'].rolling(window=20).std()
    df['bb_upper'] = df['bb_middle'] + (bb_std * 2)
    df['bb_lower'] = df['bb_middle'] - (bb_std * 2)
    df['bb_width'] = (df['bb_upper'] - df['bb_lower']) / df['bb_middle']
    
    # Volatility
    df['volatility'] = df['close'].pct_change().rolling(window=14).std()
    
    # Volume Ratio
    df['vol_ratio'] = df['volume'] / df['volume'].rolling(window=20).mean()
    
    # Target: Next candle return (Direction: 1 if up, 0 if down)
    df['next_return'] = df['close'].shift(-1) / df['close'] - 1
    df['target'] = (df['next_return'] > 0).astype(int)
    
    # Drop NaNs generated by indicators
    df.dropna(inplace=True)
    return df

print("🧮 Calculating Technical Indicators...")
for symbol in data_cache:
    data_cache[symbol] = add_indicators(data_cache[symbol])

# --- 3. Model Training & Backtesting per Symbol ---
feature_cols = [
    'rsi', 'macd', 'macd_signal', 'macd_hist', 
    'bb_width', 'volatility', 'vol_ratio',
    'sma_20', 'sma_50', 'ema_12', 'ema_26'
]

total_results = []

for symbol, df in data_cache.items():
    print(f"\n🤖 Training Model for {symbol}...")
    
    # Prepare Data
    features = df[feature_cols].values
    target = df['target'].values
    closes = df['close'].values
    timestamps = df.index
    
    # Split
    split_idx = int(len(df) * TRAIN_SPLIT)
    X_train, X_test = features[:split_idx], features[split_idx:]
    y_train, y_test = target[:split_idx], target[split_idx:]
    test_closes = closes[split_idx:]
    test_times = timestamps[split_idx:]
    
    # Scale Features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    # Train XGBoost
    model = xgb.XGBClassifier(
        n_estimators=200, 
        max_depth=6, 
        learning_rate=0.05, 
        subsample=0.8, 
        colsample_bytree=0.8,
        eval_metric='logloss',
        use_label_encoder=False
    )
    model.fit(X_train_scaled, y_train)
    
    # Evaluate Accuracy
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    print(f"📈 Model Accuracy on Test Set: {acc:.2%}")
    
    # --- Backtesting Logic ---
    balance = INITIAL_BALANCE
    trades = []
    in_position = False
    entry_price = 0
    position_size = 0
    
    # We simulate trade by trade based on model prediction
    # Prediction 1 = Buy, 0 = Do Nothing/Sell
    
    for i in range(len(X_test_scaled)):
        current_price = test_closes[i]
        signal = y_pred[i] # 1 or 0
        
        if not in_position:
            if signal == 1: # Buy Signal
                # Calculate position size based on risk
                # Risk = Balance * 1%
                # Stop Loss distance = Entry * 1.5%
                risk_amount = balance * RISK_PER_TRADE
                stop_loss_price = current_price * (1 - STOP_LOSS_PCT)
                distance = current_price - stop_loss_price
                
                if distance > 0:
                    position_size = risk_amount / distance
                    in_position = True
                    entry_price = current_price
                    entry_time = test_times[i]
        else:
            # Check Exit Conditions
            high = df.iloc[split_idx + i]['high'] # Approximate using OHLCV logic would be better, but using close for simplicity here
            low = df.iloc[split_idx + i]['low']
            
            # Did we hit TP?
            if high >= entry_price * (1 + TAKE_PROFIT_PCT):
                exit_price = entry_price * (1 + TAKE_PROFIT_PCT)
                profit = (exit_price - entry_price) * position_size
                balance += profit
                trades.append({'type': 'WIN', 'profit': profit, 'time': test_times[i]})
                in_position = False
                
            # Did we hit SL?
            elif low <= entry_price * (1 - STOP_LOSS_PCT):
                exit_price = entry_price * (1 - STOP_LOSS_PCT)
                profit = (exit_price - entry_price) * position_size
                balance += profit
                trades.append({'type': 'LOSS', 'profit': profit, 'time': test_times[i]})
                in_position = False
            
            # Optional: Force close if signal turns to 0 (Stop and Reverse logic could be added)
            elif signal == 0:
                # Simple exit at close if trend changes
                exit_price = current_price
                profit = (exit_price - entry_price) * position_size
                balance += profit
                trades.append({'type': 'SIGNAL_EXIT', 'profit': profit, 'time': test_times[i]})
                in_position = False

    # Close any open position at the end
    if in_position:
        exit_price = test_closes[-1]
        profit = (exit_price - entry_price) * position_size
        balance += profit
        trades.append({'type': 'CLOSE_END', 'profit': profit, 'time': test_times[-1]})

    # Calculate Metrics
    total_trades = len(trades)
    winning_trades = [t for t in trades if t['profit'] > 0]
    losing_trades = [t for t in trades if t['profit'] <= 0]
    
    win_rate = len(winning_trades) / total_trades if total_trades > 0 else 0
    total_profit = balance - INITIAL_BALANCE
    profit_factor = abs(sum([t['profit'] for t in winning_trades]) / sum([t['profit'] for t in losing_trades])) if losing_trades else 999
    avg_win = np.mean([t['profit'] for t in winning_trades]) if winning_trades else 0
    avg_loss = np.mean([t['profit'] for t in losing_trades]) if losing_trades else 0
    
    result = {
        'Symbol': symbol,
        'Accuracy': f"{acc:.2%}",
        'Total Trades': total_trades,
        'Win Rate': f"{win_rate:.2%}",
        'Net Profit ($)': f"{total_profit:.2f}",
        'Return (%)': f"{(total_profit/INITIAL_BALANCE)*100:.2f}%",
        'Profit Factor': f"{profit_factor:.2f}",
        'Avg Win': f"{avg_win:.2f}",
        'Avg Loss': f"{avg_loss:.2f}",
        'Final Balance': f"{balance:.2f}"
    }
    total_results.append(result)
    print(f"✅ Backtest Complete for {symbol}: Net Profit ${total_profit:.2f} ({(total_profit/INITIAL_BALANCE)*100:.2f}%)")

# --- 4. Final Report ---
print("\n" + "="*60)
print("🏆 FINAL PERFORMANCE REPORT (Advanced XGBoost Model)")
print("="*60)
results_df = pd.DataFrame(total_results)
print(results_df.to_string(index=False))

# Readiness Score Calculation
avg_win_rate = results_df['Win Rate'].str.replace('%', '').astype(float).mean()
avg_pf = results_df['Profit Factor'].astype(float).replace(999, 2.0).mean() # Cap huge PF for scoring
score = 0
if avg_win_rate > 45: score += 30
elif avg_win_rate > 40: score += 15
if avg_pf > 1.5: score += 40
elif avg_pf > 1.2: score += 20

# Calculate total net profit safely
total_profit = 0.0
for val in results_df['Net Profit ($)']:
    try:
        clean_val = str(val).replace('-', '').replace('$', '').strip()
        total_profit += float(clean_val)
    except:
        pass
        
if total_profit > 0: score += 30

print(f"\n🎯 READINESS SCORE: {score}/100")
if score >= 70:
    print("✅ STATUS: READY FOR DEMO TRADING")
elif score >= 40:
    print("⚠️ STATUS: NEEDS OPTIMIZATION (Try different parameters)")
else:
    print("❌ STATUS: NOT READY (Model needs retraining or different strategy)")

print("\n💾 Saving results to 'advanced_backtest_report.csv'...")
results_df.to_csv('advanced_backtest_report.csv', index=False)
print("Done!")
